config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'users#home'
  get 'users/new', to: 'users#new', as: 'new'
  post 'users/new', to: 'users#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def home
  end

  def new
  end

  def create
    # Uncomment pour stocker les données du 1er formulaire
    # User.create(username: params[:username], email: params[:email], bio: params[:bio])
    # Uncomment pour stocker les données du 2nd formulaire
    # User.create(username: params[:user], email: params[:email], bio: params[:bio])
    # Commenter les deux lignes au dessus pour stocker les données du 3ème formulaire
    redirect_to('/')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ILoveForms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/home.html.erb
<html>
  <head>
    <title>Bienvenue</title>
  </head>
  <body>
  <div class="home">
    <p>Hey ! Bienvenue sur notre site ! Créé par Nicolas Culerier et Nicolas Zhao !</p>
    <a href=<%= new_path %>>Inscris-toi ici</a>
  </div>
  </body>
</html>

app/views/users/new.html.erb
<!-- Premier formulaire, n'oublier de modifier le controleur des users -->
<!--
<html>
  <head>
    <title>S'enregistrer</title>
  </head>
  <body>
    <h1>S'enregistrer</h1>
    <br>
    <form method="post">
    <p>Username :</p>
    <input type="text" name="username">
    <br>
    <p>Email :</p>
    <input type="email" name="email">
    <br>
    <p>Ta biographie</p>
    <input type="textarea" name="bio">
    </form>
  </body>
</html>
-->
<!-- Second formulaire -->
<!--
<html>
  <body>
    <h1>S'enregistrer</h1>

    <%= form_tag url_for('new'), method: "post" do %>
    <%= label_tag 'Username' %>
    <%= text_field_tag :user %>
    <br>
    <%= label_tag 'Email' %>
    <%= text_field_tag :email %>
    <br>
    <%= label_tag 'Bio' %>
    <%= text_area_tag :bio %>
    <br>
    <%= submit_tag "S'enregistrer" %>

    <% end %>
  </body>
</html>
-->
<!-- Dernier Formulaire -->
<html>
  <body>
    <div class='form' style="text-align: center">
    <h1 id ="titre">S'enregistrer</h1>
    <% @user = User.new %>
    <%= form_for(@user, url: users_new_path(@user)) do |f| %>
      Username: <br> <%=f.text_field :username, class: "form-control", placeholder: "username"%> <br>
      Email: <br> <%=f.text_field :email, class: "form-control", placeholder: "email@example.com" %> <br>
      Bio: <br> <%= f.text_area :bio, class: "form-control", placeholder: "Ta magnifique bio"%> <br>
      <%= f.submit "S'enregistrer", class: "btn btn-primary" %>
      </div>
    <% end %>

  </body>
</html>